export const sampleProducts = [
	{
		ProductID: 1,
		UserName: 'Ichor',
		SupplierID: 1,
		CategoryID: 1,
		QuantityPerUnit: '10 boxes x 20 bags',
		UnitPrice: 18,
		FullName: 'James Barnes',
		UnitsOnOrder: 0,
		ReorderLevel: 10,
		Enabled: false,
		Category: {
			CategoryID: 1,
			CategoryName: 'Beverages',
			Description: 'Soft drinks, coffees, teas, beers, and ales',
		},
		LastLogin: new Date(2021, 8, 20),
	},
	{
		ProductID: 2,
		UserName: 'Yeuk',
		SupplierID: 1,
		CategoryID: 1,
		QuantityPerUnit: '24 - 12 oz bottles',
		UnitPrice: 19,
		FullName: 'James Schutz',
		UnitsOnOrder: 40,
		ReorderLevel: 25,
		Enabled: false,
		Category: {
			CategoryID: 1,
			CategoryName: 'Beverages',
			Description: 'Soft drinks, coffees, teas, beers, and ales',
		},
		LastLogin: new Date(2021, 7, 12),
	},
	{
		ProductID: 3,
		UserName: 'Sansa',
		SupplierID: 1,
		CategoryID: 2,
		QuantityPerUnit: '12 - 550 ml bottles',
		UnitPrice: 10,
		FullName: 'Marcia Delph',
		UnitsOnOrder: 70,
		ReorderLevel: 25,
		Enabled: false,
		Category: {
			CategoryID: 2,
			CategoryName: 'Condiments',
			Description: 'Sweet and savory sauces, relishes, spreads, and seasonings',
		},
		LastLogin: new Date(2021, 8, 26),
	},
	{
		ProductID: 4,
		UserName: 'Stoichiology',
		SupplierID: 2,
		CategoryID: 2,
		QuantityPerUnit: '48 - 6 oz jars',
		UnitPrice: 22,
		FullName: 'Marcus Brown',
		UnitsOnOrder: 0,
		ReorderLevel: 0,
		Enabled: false,
		Category: {
			CategoryID: 2,
			CategoryName: 'Condiments',
			Description: 'Sweet and savory sauces, relishes, spreads, and seasonings',
		},
		LastLogin: new Date(2021, 9, 19),
	},
	{
		ProductID: 5,
		UserName: 'Chrispyme',
		SupplierID: 2,
		CategoryID: 2,
		QuantityPerUnit: '36 boxes',
		UnitPrice: 21.35,
		FullName: 'Thomas Gaines',
		UnitsOnOrder: 0,
		ReorderLevel: 0,
		Enabled: true,
		Category: {
			CategoryID: 2,
			CategoryName: 'Condiments',
			Description: 'Sweet and savory sauces, relishes, spreads, and seasonings',
		},
		LastLogin: new Date(2021, 7, 17),
	},
	{
		ProductID: 6,
		UserName: 'Czarcat',
		SupplierID: 3,
		CategoryID: 2,
		QuantityPerUnit: '12 - 8 oz jars',
		UnitPrice: 25,
		FullName: 'Rod Messina',
		UnitsOnOrder: 0,
		ReorderLevel: 25,
		Enabled: false,
		Category: {
			CategoryID: 2,
			CategoryName: 'Condiments',
			Description: 'Sweet and savory sauces, relishes, spreads, and seasonings',
		},
		LastLogin: new Date(2021, 9, 19),
	},
	{
		ProductID: 7,
		UserName: 'Xx_lronman_',
		SupplierID: 3,
		CategoryID: 7,
		QuantityPerUnit: '12 - 1 lb pkgs.',
		UnitPrice: 30,
		FullName: 'Myrtle Kaufmann',
		UnitsOnOrder: 0,
		ReorderLevel: 10,
		Enabled: false,
		Category: {
			CategoryID: 7,
			CategoryName: 'Produce',
			Description: 'Dried fruit and bean curd',
		},
		LastLogin: new Date(2021, 7, 22),
	},
	{
		ProductID: 8,
		UserName: 'Anbe84',
		SupplierID: 3,
		CategoryID: 2,
		QuantityPerUnit: '12 - 12 oz jars',
		UnitPrice: 40,
		FullName: 'Ann Groesbeck',
		UnitsOnOrder: 0,
		ReorderLevel: 0,
		Enabled: false,
		Category: {
			CategoryID: 2,
			CategoryName: 'Condiments',
			Description: 'Sweet and savory sauces, relishes, spreads, and seasonings',
		},
		LastLogin: new Date(2021, 11, 1),
	},
	{
		ProductID: 9,
		UserName: 'Thewind',
		SupplierID: 4,
		CategoryID: 6,
		QuantityPerUnit: '18 - 500 g pkgs.',
		UnitPrice: 97,
		FullName: 'Carie Hale',
		UnitsOnOrder: 0,
		ReorderLevel: 0,
		Enabled: true,
		Category: {
			CategoryID: 6,
			CategoryName: 'Meat/Poultry',
			Description: 'Prepared meats',
		},
		LastLogin: new Date(2021, 1, 21),
	},
	{
		ProductID: 10,
		UserName: 'Eidolon',
		SupplierID: 4,
		CategoryID: 8,
		QuantityPerUnit: '12 - 200 ml jars',
		UnitPrice: 31,
		FullName: 'Ada Harville',
		UnitsOnOrder: 0,
		ReorderLevel: 0,
		Enabled: false,
		Category: {
			CategoryID: 8,
			CategoryName: 'Seafood',
			Description: 'Seaweed and fish',
		},
		LastLogin: new Date(2021, 8, 5),
	},
];
